codecov:
  require_ci_to_pass: yes
  comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: no
    require_base: no
    require_head: no
  notify:
    require_ci_to_pass: yes
    after_n_builds: 5
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        paths:
          - "lib/"
          - "test/"
